port: 8080
mode: dev

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "distill"

redis:
  addr: "localhost:6379"
  db: 0
  password:

log:
  level: 'info'
  filename: "app.log"
  max_size: 100
  max_age: 100
  max_backups: 100

llm:
  api_key: "sk-2c4e9ad917cf48d8ad834dc5b98e7e01"
  model: "deepseek-reasoner"
  base_url : "https://api.deepseek.com"

youtube:
 api_key: "AIzaSyAzI_7kpR8HYEkWg-J_RX4c2YNAPumby1o"